stages:
  - build
  - test
  - release

.dotnet-job: &dotnet-job
  image: mcr.microsoft.com/dotnet/sdk:8.0

build:
  <<: *dotnet-job
  stage: build
  script:
    - dotnet build

test:
  <<: *dotnet-job
  stage: test
  variables:
    CONFIGURATION: "Debug"
    COVERAGE_FLAG: "XPlat Code Coverage"
    LOGGER_FLAG: "junit;LogFilePath=$CI_PROJECT_DIR/junit/junit-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  script:
    - 'dotnet test DotNetSolution 
        --collect:"XPlat Code Coverage"
        --results-directory cobertura'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura/*/coverage.cobertura.xml


build-executable:
  <<: *dotnet-job
  stage: release
  only:
    - master
    - main
  script:
    - dotnet publish OTA_CLI/OTA_CLI.csproj -c Release -r win-x64 -o ./tmp/build-artifact --self-contained /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true
  artifacts:
    paths:
      - ./tmp/build-artifact
