stages:
  - build
  - test
  - release

.dotnet-job: &dotnet-job
  image: mcr.microsoft.com/dotnet/sdk:8.0

build:
  <<: *dotnet-job
  stage: build
  script:
    - dotnet build

test:
  <<: *dotnet-job
  stage: test
  script:
    - dotnet test

build-executable:
  <<: *dotnet-job
  stage: release
  script:
    - dotnet publish OTA_CLI/OTA_CLI.csproj --self-contained -c Release -r win-x64  --no-restore -o  ./tmp/build-artifact
  artifacts:
    paths:
      - ./tmp/build-artifact
